# Generated by Django 5.2.17 on 2026-09-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
