# Generated by Django 5.2.17 on 2026-09-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_alter_token_doctor_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='original_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_tokens', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='token',
            name='original_token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
